config/routes.rb
PATS67272::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
  resources :users
  
  # Generated model routes
  resources :owners do
	resources :notes
  end
  resources :animals
  resources :pets do
	resources :notes
  end
  resources :visits do
	resources :notes    
  end 
  resources :medicines
  resources :procedures
  resources :medicine_costs
  resources :procedure_costs
  resources :animal_medicines
  resources :notes
  
  # Semi-static page routes
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  
  # Set the root url
  root :to => 'home#index'
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  
  # Relationships
  # -----------------------------
  belongs_to :pet
  has_one :owner, :through => :pet
  has_many :visit_medicines
  has_many :medicines, :through => :visit_medicines
  has_many :treatments
  has_many :procedures, :through => :treatments
  has_many :notes, :as => :notable, :dependent => :destroy
 
  # Scopes
  # -----------------------------
  # by default, order by visits in descending order (most recent first)
   scope :chronological, order('date DESC')
   # get all the visits by a particular pet
   scope :for_pet, lambda {|pet_id| where('pet_id = ?', pet_id) }
   # get the last X visits
   scope :last, lambda {|num| limit(num).order('date DESC') }
   # get all visits that resulted in overnight stay
   scope :overnights, where('overnight_stay = ?', true)
  
  # Validations
  # -----------------------------
  validates_presence_of :pet_id
  validates_date :date
  # weight must be an integer greater than 0 and less than 100 (none of our animal types will exceed)
  validates_numericality_of :weight, :only_integer => true, :greater_than => 0, :less_than => 100, :allow_blank => true
  validates_numericality_of :total_charge, :only_integer => true, :greater_than_or_equal_to => 0
  
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def index
    # get all visits in reverse chronological order, 10 per page
    @visits = Visit.chronological.paginate(:page => params[:page]).per_page(10)
  end
  
  def show
    # get the data for this particular visit
    @visit = Visit.find(params[:id])
    # get all the vaccinations associated with this visit, if any
   #@vaccinations = @visit.vaccinations
    @notes = @visit.notes
    @notable = @visit
  end
  
  def new
    @visit = Visit.new
  end
  
  def create
    @visit = Visit.new(params[:visit])
    if @visit.save
      flash[:notice] = "Successfully added visit for #{@visit.pet.name}."
      redirect_to @visit
    else
      render :action => 'new'
    end
  end
  
  def edit
    @visit = Visit.find(params[:id])
  end
  
  def update
    @visit = Visit.find(params[:id])
    if @visit.update_attributes(params[:visit])
      flash[:notice] = "Successfully updated visit by #{@visit.pet.name}."
      redirect_to @visit
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy
    flash[:notice] = "Successfully removed the visit of #{@visit.pet.name} on #{@visit.date.strftime('%b %e')}."
    redirect_to visits_url
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
  # create a helper to get the options for the pet select menu
  # will return an array with key being pet_name : owner_name so 
  # that vet can choose the right pet (many pets share same names)
  def get_pet_options
    Pet.active.alphabetical.map{|p| ["#{p.name} (#{p.animal.name}) : #{p.owner.name}", p.id] }
  end
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pet_id %><br />
    <%= f.select :pet_id, get_pet_options, :prompt => "Select ..." %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date, :order => [:month, :day, :year] %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Visits to PATS</h1><br>

<table class="datagrid">
  <thead class="datagrid">
    <th>Date</th>
    <th>Pet</th>
	<th>Weight</th>
	<th>&nbsp;</th>
  </thead>
  <% for visit in @visits %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to visit.date.strftime("%m/%d/%y"), visit_path(visit) %></td>
      <td><%= link_to visit.pet.name, pet_path(visit.pet) %> (<%= visit.pet.animal.name %>)</td>
      <td align="center"><%= visit.weight %> lbs</td>
	  <td align="center">
		<%= link_to(image_tag("icons/edit_dg.gif", :border => 0), edit_visit_path(visit))  %>&nbsp;
		<%= link_to(image_tag("icons/delete_dg.gif", :border => 0), visit_path(visit), :confirm => 'Are you sure you wish to delete this information?', :method => :delete) %>
	  </td>
    </tr>
  <% end %>
</table>
<p class="supertiny"></p>

<!-- Add the pagination using will_paginate gem -->
<span class="smtext">
<%= will_paginate @visits, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

<p><strong><%= link_to "Add A New Visit", new_visit_path %></strong></p>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<h2>Visit Information</h2>
<p>
  <strong>Pet:</strong>
  <%= link_to @visit.pet.name, pet_path(@visit.pet) %>
</p>
<p>
  <strong>Owner:</strong>
  <%= link_to "#{@visit.pet.owner.first_name} #{@visit.pet.owner.last_name}", owner_path(@visit.pet.owner) %>
</p>
<p>
  <strong>Animal:</strong>
  <%= @visit.pet.animal.name %>
</p>
<p>
  <strong>Visit Date:</strong>
  <%= @visit.date.strftime("%B %d, %Y") %>
</p>
<p>
  <strong>Weight:</strong>
  <%= @visit.weight %> lbs.
</p>
<p class="supertiny">&nbsp;</p>
<p>
  <%= link_to "Edit", edit_visit_path(@visit) %> |
  <%= link_to "Destroy", @visit, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", visits_path %>
</p>
<%= render :partial => "partials/add_notes_to_page", :locals => {:obj => @visit} %> 