config/routes.rb
PATS67272::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
  resources :users
  
  # Generated model routes
  resources :owners do
	resources :notes
  end
  resources :animals
  resources :pets do
	resources :notes
  end
  resources :visits do
	resources :notes    
  end 
  resources :medicines
  resources :procedures
  resources :medicine_costs
  resources :procedure_costs
  resources :animal_medicines
  resources :notes
  
  # Semi-static page routes
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  
  # Set the root url
  root :to => 'home#index'
end

app/models/pet.rb
class Pet < ActiveRecord::Base

  # Relationships
  # -----------------------------
  belongs_to :owner
  belongs_to :animal
  has_many :visits
  has_many :visit_medicines, :through => :visits
  has_many :medicines, :through => :visit_medicines
  has_many :notes, :as => :notable, :dependent => :destroy

  # Scopes
  # -----------------------------
  # order pets by their name
  scope :alphabetical, order('name')
  # get all the pets we treat (not moved away or dead)
  scope :active, where('active = ?', true)
  # get all the pets we no longer treat (e.g., moved away or dead)
  scope :inactive, where('active = ?', false)
  # get all the female pets
  scope :females, where('female = ?', true)
  # get all the male pets
  scope :males, where('female = ?', false)

  # get all the pets for a particular owner
  scope :for_owner, lambda {|owner_id| where("owner_id = ?", owner_id) }
  # get all the pets who are a particular animal type
  scope :by_animal, lambda {|animal_id| where("animal_id = ?", animal_id) }
  # get all the pets born before a certain date
  scope :born_before, lambda {|dob| where('date_of_birth < ?', dob) }
  # find all pets that have a name like some term or are and animal like some term
  scope :search, lambda { |term| joins(:animal).where('pets.name LIKE ?', "#{term}%").order("pets.name") }


  # Validations
  # -----------------------------
  # System note:   not requiring DOB because may not be known (e.g., adopted pet)
  # Teaching note: could have done validates_presence_of :name, but using a different
  #                method discussed in class to show alternative
  #
  # First, make sure a name exists
  validates :name, :presence => true
  # Second, make sure the animal is one of the types PATS treats
  validate :animal_type_treated_by_PATS
  # Third, make sure the owner_id is in the PATS system 
  validate :owner_is_active_in_PATS_system
  

  # Misc Methods and Constants
  # -----------------------------
  # a method to get owner name in last, first format
  def gender
    return "Female" if female
    "Male"
  end  
  
  
  # Use private methods to execute the custom validations
  # -----------------------------
  private
  def animal_type_treated_by_PATS
    # get an array of all animal ids PATS treats
    treated_animal_ids = Animal.all.map{|a| a.id}
    # add error unless the animal id of the pet is in the array of possible animal ids
    unless treated_animal_ids.include?(self.animal_id)
      errors.add(:animal, "is an animal type not treated by PATS")
      return false   # not necessary, but I like to add it ...
    end
    return true  # also not strictly necessary ...
  end
  
  def owner_is_active_in_PATS_system
    # get an array of all active owners in the PATS system
    all_owner_ids = Owner.active.all.map{|o| o.id}
    # add error unless the owner id of the pet is in the array of active owners
    unless all_owner_ids.include?(self.owner_id)
      errors.add(:owner, "is not an active owner in PATS")
      return false
    end
    return true
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  respond_to :html, :xml, :json
  
  def index
    # get data on all pets and paginate the output to 10 per page
    @pets = Pet.active.alphabetical.paginate(:page => params[:page]).per_page(10)
    respond_with @pets

  end

  def show
    # get the data for this particular pet
    @pet = Pet.find(params[:id])
    # get the last 10 visits for this pet
    @recent_visits = @pet.visits.all.last(10)
    @notes = @pet.notes
    @notable = @pet
    respond_with @pet 
  end

  def new
    @pet = Pet.new
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def create
    @pet = Pet.new(params[:pet])
    if @pet.save
      redirect_to @pet, :notice => "Successfully added #{@pet.name} as a PATS pet."
    else
      render :action => 'new'
    end
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update_attributes(params[:pet])
      redirect_to @pet, :notice => "Updated #{@pet.name}'s information"
    else
      render :action => 'edit'
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_url, :notice => "Removed #{@pet.name} from the PATS system"
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :animal_id %><br />
    <%= f.collection_select :animal_id, Animal.all, :id, :name, :prompt => "Select ..." %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br />
    <%= f.collection_select :owner_id, Owner.active.all, :id, :name, :prompt => "Select ..." %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :female %><br />
    <%= f.check_box :female %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth, :order => [:month, :day, :year] %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/_pet_data.html.erb
<td width="300">
	<h2>Pet Information:</h2>
	<b>Name:&nbsp;&nbsp;</b>
	  <%= @pet.name %><br /><br />

	<b>Owner:&nbsp;&nbsp;</b>
	  <%= link_to @pet.owner.name, owner_path(@pet.owner) %><br /><br />

	<b>Type:&nbsp;&nbsp;</b>
	  <%= @pet.animal.name %><br /><br />

	<b>Gender:&nbsp;&nbsp;</b>
	  <%= @pet.gender %><br /><br />

	<b>Date of Birth:&nbsp;&nbsp;</b>
	  <%= @pet.date_of_birth.strftime("%B %d, %Y") %><br /><br />

	<b>Active with PATS?:&nbsp;&nbsp;</b>
	  <%= @pet.active %><br><br><br>

	  <%= link_to "Edit", edit_pet_path(@pet) %> |
	  <%= link_to "Destroy", @pet, :confirm => 'Are you sure?', :method => :delete %> |
	  <%= link_to "View All", pets_path %>
</td>
<td width="10">&nbsp;</td>

app/views/pets/_recent_visits.html.erb
<td width="250">
	<h2>Recent Visits:</h2>
	<table class="datagrid">
	  <thead class="datagrid">
	    <th width="90">Visit</th>
		<th width="60">Weight</th>
	  </thead>
  
	<% for visit in @recent_visits %>
	  <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
	    <td align="left"><%= link_to visit.date.strftime("%m/%d/%y"), visit_path(visit) %></td>
		<td align="left">&nbsp;<%= visit.weight %> lbs</td>
	  </tr>
	<% end %>
	</table>
	<p class="supertiny">&nbsp;</p>
</td>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Active Pets at PATS</h1><br>

<table class="datagrid">
  <thead class="datagrid">
    <th>Pet</th>
		<th>Type</th>
    <th>Owner</th>
	<th>&nbsp;</th>
  </thead>
  <% for pet in @pets %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to pet.name, pet_path(pet) %></td>
      <td><%= pet.animal.name %></td>
      <td><%= link_to pet.owner.name, owner_path(pet.owner) %></td>

	  <td align="center">
			<%= link_to(image_tag("icons/edit_dg.gif", :border => 0), edit_pet_path(pet))  %>&nbsp;
			<%= link_to(image_tag("icons/delete_dg.gif", :border => 0), pet_path(pet), :confirm => 'Are you sure you wish to delete this information?', :method => :delete) %>
	  </td>
    </tr>
  <% end %>
</table>
<p class="supertiny"></p>

<!-- Add the pagination using will_paginate gem -->
<span class="smtext">
<%= will_paginate @pets, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

<p><strong><%= link_to "Add A New Pet", new_pet_path %></strong></p>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<table>
	<tr valign="top">			
		<%= render :partial => "pet_data" %>		
	
		<% unless @recent_visits.empty? %>
		  <%= render :partial => "recent_visits" %>
		<% end %>
	</tr>
</table>
<p class="supertiny">&nbsp;</p>
<%= render :partial => "partials/add_notes_to_page", :locals => {:obj => @pet} %>