config/routes.rb
PATS67272::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
  resources :users
  
  # Generated model routes
  resources :owners do
	resources :notes
  end
  resources :animals
  resources :pets do
	resources :notes
  end
  resources :visits do
	resources :notes    
  end 
  resources :medicines
  resources :procedures
  resources :medicine_costs
  resources :procedure_costs
  resources :animal_medicines
  resources :notes
  
  # Semi-static page routes
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  
  # Set the root url
  root :to => 'home#index'
end

app/views/partials/_add_notes_to_page.html.erb
<p>
	<strong><%= obj.notes.size.zero? ? "No notes yet" : pluralize(obj.notes.size, 'note') %> on this <%= "#{obj.class.to_s.downcase}" %></strong><br>
	<% unless @notes.empty? || @notes.nil? %>
		<%= render :partial => "partials/note_list" %>
	<% end %>
</p>
<p>
	<%= render :partial => "partials/note_form" %>
</p>

app/views/partials/_animal_pics.html.erb
<div id="animal_pics">
	<%= image_tag 'aminal_collage_sm.jpg' %>
	
	<p>&nbsp;</p>
</div> <!-- end of animal_pics div -->

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer">
	
	<%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About PATS', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Privacy Policy', privacy_path %>
	<br /><br />
	<div id="copy">
		Webmaster: <%= mail_to("profh@cmu.edu", "Klingon Code Warrior", :encode => "javascript") %> 
		&nbsp;&nbsp;&copy 2012
	</div>

</div>

app/views/partials/_navigation.html.erb
<div id="nav">
	<ul>
	<!-- OPTIONS FOR EVERYONE -->
		<!--<li><em>Option: </em></li>-->
		<li><%= link_to 'Owners', owners_path %></li>
		<li><%= link_to 'Pets', pets_path %></li>
		<li><%= link_to 'Visits', visits_path %></li>
		<li><%= link_to 'Vaccinations', vaccinations_path %></li>
		
		<li><%= link_to 'Login', 'http://www.google.com' %></li>
	</ul>
</div> <!-- end of nav div -->

app/views/partials/_note_form.html.erb
<p class="supertiny">&nbsp;</p>
<h3>Add a Note</h3><br />

<%= form_for([@notable, Note.new], :html => { :class => 'form-horizontal' }) do |f| %>
  <fieldset>
    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :content, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :content, :class => 'text_area', :rows => 4 %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', home_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/partials/_note_list.html.erb
<div id="notes">
<% for note in @notes %>
  <div class="note">
    <strong><%= note.title %></strong><br>
    <%= note.content %><br>	
		by <strong><%= note.user.proper_name %></strong>
	  <em>on <%= note.date.strftime('%b %d, %Y') %></em>
  </div>
<% end %>
</div>

app/views/partials/_side_nav.html.erb
<div id="side_nav">
	<h3>Vet Options:</h3>
	
	<ul>
	<!-- OPTIONS FOR EVERYONE -->
		<li>
			<%= form_tag(search_path) do %>
				<%= text_field_tag('query', '', :size => 12) %>
				<%= submit_tag('Find') %>
			<% end %>
		</li>
		<li><%= link_to 'Owners', owners_path %></li>
		<li><%= link_to 'Pets', pets_path %></li>
		<li><%= link_to 'Visits', visits_path %></li>
		<li><%= link_to 'Medicines', medicines_path %></li>
	  <li><%= link_to 'Procedures', procedures_path %></li>
		<!-- can set this manually, or just use the named route 'logout' -->
		<li>
			<%# link_to 'Logout', { :controller => :sessions, :action => :destroy } %>
			<%= link_to 'Logout', logout_path %>
		</li>
	</ul>
	<p>&nbsp;</p>
</div> <!-- end of side_nav div -->