config/routes.rb
PATS67272::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
  resources :users
  
  # Generated model routes
  resources :owners do
	resources :notes
  end
  resources :animals
  resources :pets do
	resources :notes
  end
  resources :visits do
	resources :notes    
  end 
  resources :medicines
  resources :procedures
  resources :medicine_costs
  resources :procedure_costs
  resources :animal_medicines
  resources :notes
  
  # Semi-static page routes
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  
  # Set the root url
  root :to => 'home#index'
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  # Relationships
  # -----------------------------
  has_many :pets
  has_many :vaccines
  has_many :animal_medicines
  has_many :medicines, :through => :animal_medicines
  
  # Scopes
  # -----------------------------
  scope :alphabetical, order('name')
  scope :active, where('active = ?', true)
  scope :inactive, where('active = ?', false)
   
  # Validations
  # -----------------------------
  validates_presence_of :name
  
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    @animals = Animal.all
  end

  def show
     # get data on that particular animal
      @animal = Animal.find(params[:id])
      # get all the pets of that animal type that have been treated by PATS
      @pets = Pet.by_animal(@animal.id).paginate(:page => params[:page]).per_page(10)
  end

  def new
    @animal = Animal.new
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def create
    @animal = Animal.new(params[:animal])
    if @animal.save
      flash[:notice] = "Successfully created animal."
      redirect_to @animal
    else
      render :action => 'new'
    end
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update_attributes(params[:animal])
      flash[:notice] = "Successfully updated animal."
      redirect_to @animal
    else
      render :action => 'edit'
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    flash[:notice] = "Successfully destroyed animal."
    redirect_to animals_url
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<h1>Animals Treated at PATS</h1><br>

<table class="datagrid">
  <thead class="datagrid">
    <th>Animal</th>
    <th>Treated Here Since</th>
		<th>&nbsp;</th>
  </thead>
  <% for animal in @animals %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to animal.name, animal_path(animal) %></td>
	  <td align="center"><%= animal.created_at.strftime("%B %d, %Y") %></td>
	  <td align="center">
		<%= link_to(image_tag("icons/edit_dg.gif", :border => 0), edit_animal_path(animal))  %>&nbsp;
		<%= link_to(image_tag("icons/delete_dg.gif", :border => 0), animal_path(animal), :confirm => 'Are you sure you wish to delete this information?', :method => :delete) %>
	  </td>
    </tr>
  <% end %>
</table>
<p class="supertiny"></p>

<p><strong><%= link_to "Add A New Animal", new_animal_path %></strong></p>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<h1>All the <%= @animal.name.capitalize.pluralize %> Treated at PATS</h1><br>

<table class="datagrid">
  <thead class="datagrid">
    <th width="90">Pet</th>
	<th width="150">Owner</th>
  </thead>
  
<% for pet in @pets %>
  <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
    <td align="left"><%= link_to pet.name, pet_path(pet) %></td>
	<td align="left"><%= link_to pet.owner.name, owner_path(pet.owner) %></td>
  </tr>
<% end %>
</table>
<p class="supertiny"></p>

<!-- Add the pagination using will_paginate gem -->
<span class="smtext">
<%= will_paginate @pets, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>
<p>
  <%= link_to "Back to All Animals", animals_path %>
</p>